project:
  group: slipper
  name: slipper

service:
  port: 8806
  context-path: /slipper

database:
  ip: 139.196.182.46
  port: 3306
  name: slipper-admin-base
  username: root
  password: ll5271211314

druid:
  url-pattern: /druid/*
  username: gumingchen
  password: gumingchen

token:
  expire: 36000

redis:
  host: localhost
  port: 6379
  password:
