project:
  group: slipper
  name: slipper

service:
  port: 8806
  context-path: /slipper

database:
  ip: localhost
  port: 3306
  name: slipper-admin-base
  username: root
  password: root

druid:
  url-pattern: /druid/*
  username:
  password:

token:
  expire: 7200

redis:
  host: localhost
  port: 6379
  password:
